steps:
#First Clone from Github Source Repository  
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/kchaitu4/company.git']

#Build the image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}','.']

#Push the image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']
  
#Update the container image using kubectl set
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENTNAME}'
  # - 'namespace/${_NAMESPACE}'
  - '${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'

  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  
substitutions:
    #GCP Specific configuration. Please Note: _PROJECT = PROJECT from GCP, _ZONE = whereever the cluster is located, _GKE_CLUSTER = Name of the cluster 
    _PROJECT: kubernetes-283707
    _ZONE: us-central1-a
    _GKE_CLUSTER: company-cluster-1
    
    #Repository Specific configuration. Plese Note: _DEPLOYMENTNAME = app that we deployed, _CONTAINERNAME = name of the container you get when you describe a pod, 
    _DEPLOYMENTNAME: testapp
    _CONTAINERNAME: company-1
    _REPO_NAME: company
    # _NAMESPACE: conpmany-namespace ::: can be used incase the deployed app is not in default namespace
    
    # ONLY Plase for Developers to make changes in this file each time they do a deployment
    _VERSION: v1.3
    
options:
    substitution_option: 'ALLOW_LOOSE'